# import = [ "./light_theme.toml" ]

[window]
opacity = 1.0
decorations = "Transparent"
startup_mode = "Windowed"
dynamic_title = true
dynamic_padding = false
padding = { x = 8, y = 24 }
dimensions = { columns = 80, lines = 24 }
position = { x = 0, y = 0 }

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 12.0

[scrolling]
history = 4000
multiplier = 3

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

# ===== Key Bindings =====
[[keyboard.bindings]]
key = "K"
mods = "Command"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "C"
mods = "Command"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Command"
action = "Paste"

[[keyboard.bindings]]
key = "Equals"
mods = "Command"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Command"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Command"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001bb"  # ESC + b: backward-word

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001bf"  # ESC + f: forward-word

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001"   # ^A: start of line

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005"   # ^E: end of line

[general]
# ===== Import Theme =====
import = [ "./dark_theme.toml" ]
